#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iNQUIRE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="djatoka_test")]
	public partial class DjatokaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDjatokaResource(DjatokaResource instance);
    partial void UpdateDjatokaResource(DjatokaResource instance);
    partial void DeleteDjatokaResource(DjatokaResource instance);
    #endregion
		
		public DjatokaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["djatoka_testConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DjatokaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DjatokaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DjatokaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DjatokaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DjatokaResource> DjatokaResources
		{
			get
			{
				return this.GetTable<DjatokaResource>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.resources")]
	public partial class DjatokaResource : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _identifier;
		
		private string _imageFile;
		
		private System.Nullable<System.DateTime> _lastedited;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidentifierChanging(string value);
    partial void OnidentifierChanged();
    partial void OnimageFileChanging(string value);
    partial void OnimageFileChanged();
    partial void OnlasteditedChanging(System.Nullable<System.DateTime> value);
    partial void OnlasteditedChanged();
    #endregion
		
		public DjatokaResource()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifier", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string identifier
		{
			get
			{
				return this._identifier;
			}
			set
			{
				if ((this._identifier != value))
				{
					this.OnidentifierChanging(value);
					this.SendPropertyChanging();
					this._identifier = value;
					this.SendPropertyChanged("identifier");
					this.OnidentifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imageFile", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string imageFile
		{
			get
			{
				return this._imageFile;
			}
			set
			{
				if ((this._imageFile != value))
				{
					this.OnimageFileChanging(value);
					this.SendPropertyChanging();
					this._imageFile = value;
					this.SendPropertyChanged("imageFile");
					this.OnimageFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastedited", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastedited
		{
			get
			{
				return this._lastedited;
			}
			set
			{
				if ((this._lastedited != value))
				{
					this.OnlasteditedChanging(value);
					this.SendPropertyChanging();
					this._lastedited = value;
					this.SendPropertyChanged("lastedited");
					this.OnlasteditedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
