<?xml version="1.0" encoding="utf-8"?><Database Name="djatoka_test" Class="DjatokaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ARMSERV;Initial Catalog=djatoka_test;Persist Security Info=True;User ID=djatoka" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="djatoka_testConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.resources" Member="DjatokaResources">
    <Type Name="DjatokaResource">
      <Column Name="identifier" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="imageFile" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="lastedited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>